import { z } from 'zod';

// ============================================================================
// 1. AI Lead Qualification Schemas & Types
// ============================================================================

export const AiQualificationInputSchema = z.object({
  message: z.string().max(8000, 'Message exceeds 8000 character maximum limit'),
  service_interest: z.string().max(500).optional().nullable(),
  company: z.string().max(500).optional().nullable(),
  estimated_budget: z.union([z.number(), z.string()]).optional().nullable(),
  lead_name: z.string().max(200).optional().nullable(),
  additional_context: z.record(z.string(), z.any()).optional().nullable(),
});

export type AiQualificationInput = z.infer<typeof AiQualificationInputSchema>;

export const AiQualificationResultSchema = z.object({
  category: z.string().min(1, 'Category cannot be empty'),
  qualification_score: z.number().int().min(0).max(100),
  priority: z.enum(['low', 'medium', 'high']),
  summary: z.string().min(1, 'Summary cannot be empty'),
  suggested_next_action: z.string().min(1, 'Suggested next action cannot be empty'),
  lead_tier: z.enum(['hot', 'warm', 'cold', 'unqualified']),
  intent_signals: z.array(z.string()).default([]),
  budget_analysis: z.string().optional().nullable(),
  explanation_disclaimer: z.string().default('Estimates generated by AI based on lead input'),
});

export type AiQualificationResult = z.infer<typeof AiQualificationResultSchema>;

// ============================================================================
// 2. Text Classification Schemas & Types
// ============================================================================

export const AiTextClassificationInputSchema = z.object({
  text: z.string().max(8000, 'Text exceeds 8000 character maximum limit'),
  candidate_labels: z.array(z.string().min(1)).min(2, 'At least 2 candidate labels required'),
  task_description: z.string().max(1000).optional().nullable(),
});

export type AiTextClassificationInput = z.infer<typeof AiTextClassificationInputSchema>;

export const AiTextClassificationResultSchema = z.object({
  classification: z.string().min(1),
  confidence: z.number().min(0).max(1),
  reasoning: z.string().min(1),
});

export type AiTextClassificationResult = z.infer<typeof AiTextClassificationResultSchema>;

// ============================================================================
// 3. Email Response Drafting Schemas & Types
// ============================================================================

export const AiEmailDraftInputSchema = z.object({
  lead_name: z.string().min(1),
  lead_message: z.string().max(8000),
  company: z.string().optional().nullable(),
  service_interest: z.string().optional().nullable(),
  tone: z.enum(['professional', 'friendly', 'urgent', 'consultative']).default('professional'),
  instructions: z.string().max(1000).optional().nullable(),
  sender_name: z.string().optional().nullable(),
  company_name: z.string().optional().nullable(),
});

export type AiEmailDraftInput = z.infer<typeof AiEmailDraftInputSchema>;

export const AiEmailDraftResultSchema = z.object({
  subject: z.string().min(1),
  body_text: z.string().min(1),
  body_html: z.string().min(1),
  call_to_action: z.string().min(1),
  tone: z.string(),
  is_draft: z.literal(true),
  explanation_disclaimer: z.string().default('AI-generated response draft — review before sending'),
});

export type AiEmailDraftResult = z.infer<typeof AiEmailDraftResultSchema>;

// ============================================================================
// 4. Usage & Metadata Types
// ============================================================================

export interface AiUsageMetadata {
  model: string;
  provider: 'openai' | 'mock_demo' | 'fallback';
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  latency_ms: number;
  timestamp: string;
}

export interface AiExecutionOptions {
  workspaceId?: string;
  timeoutMs?: number;
  maxRetries?: number;
  modelOverride?: string;
  temperature?: number;
}
