import type { AiProvider } from './provider';
import {
  AiQualificationInput,
  AiQualificationResult,
  AiQualificationResultSchema,
  AiTextClassificationInput,
  AiTextClassificationResult,
  AiTextClassificationResultSchema,
  AiEmailDraftInput,
  AiEmailDraftResult,
  AiEmailDraftResultSchema,
  AiUsageMetadata,
  AiExecutionOptions,
} from '@/types/ai';

export class MockAiAdapter implements AiProvider {
  public readonly name = 'mock_demo';

  async qualifyLead(
    input: AiQualificationInput,
    _options?: AiExecutionOptions
  ): Promise<{ result: AiQualificationResult; metadata: AiUsageMetadata }> {
    const startTime = performance.now();

    const rawBudget = input.estimated_budget;
    let numericBudget = 0;
    if (typeof rawBudget === 'number') {
      numericBudget = rawBudget;
    } else if (typeof rawBudget === 'string') {
      numericBudget = parseFloat(rawBudget.replace(/[^0-9.]/g, '')) || 0;
    }

    const msgLower = (input.message || '').toLowerCase();
    const serviceLower = (input.service_interest || '').toLowerCase();

    // Deterministic rule-based scoring for demo / offline environments
    let score = 65;
    let tier: 'hot' | 'warm' | 'cold' | 'unqualified' = 'warm';
    let priority: 'low' | 'medium' | 'high' = 'medium';
    const signals: string[] = [];

    if (numericBudget >= 20000 || msgLower.includes('enterprise') || msgLower.includes('urgent') || msgLower.includes('asap')) {
      score = Math.min(95, 80 + Math.floor((numericBudget / 10000) * 2));
      tier = 'hot';
      priority = 'high';
      signals.push('High estimated budget ($' + numericBudget.toLocaleString() + ')');
      if (msgLower.includes('urgent') || msgLower.includes('asap')) signals.push('Urgent timeline requirement');
    } else if (numericBudget >= 5000 || msgLower.includes('ready to start') || msgLower.includes('growth')) {
      score = 78;
      tier = 'warm';
      priority = 'medium';
      signals.push('Solid commercial interest');
    } else if (numericBudget > 0 && numericBudget < 2000) {
      score = 42;
      tier = 'cold';
      priority = 'low';
      signals.push('Sub-threshold initial budget estimate');
    } else if (msgLower.includes('spam') || msgLower.includes('crypto') || msgLower.includes('seo backlink')) {
      score = 15;
      tier = 'unqualified';
      priority = 'low';
      signals.push('Unrelated promotional inquiry');
    }

    let category = 'General Inbound Inquiry';
    if (serviceLower.includes('ai') || msgLower.includes('automation') || msgLower.includes('bot')) {
      category = 'AI & Process Automation';
    } else if (serviceLower.includes('web') || serviceLower.includes('app') || msgLower.includes('software')) {
      category = 'Custom Software Development';
    } else if (serviceLower.includes('consulting') || msgLower.includes('advisory')) {
      category = 'Strategic Consulting';
    }

    const companyStr = input.company ? ` from ${input.company}` : '';
    const nameStr = input.lead_name || 'Prospect';
    const summary = `${nameStr}${companyStr} inquired regarding ${input.service_interest || 'services'}. Expressed interest: "${input.message.slice(0, 120)}${input.message.length > 120 ? '...' : ''}"`;

    let suggestedAction = 'Send standard welcome email and company portfolio';
    if (tier === 'hot') {
      suggestedAction = 'Schedule priority discovery call with senior solutions architect within 4 hours';
    } else if (tier === 'warm') {
      suggestedAction = 'Dispatch tailored capability deck and automated calendar scheduling link';
    } else if (tier === 'cold' || tier === 'unqualified') {
      suggestedAction = 'Route to self-serve knowledge base and standard nurture newsletter';
    }

    const result = AiQualificationResultSchema.parse({
      category,
      qualification_score: score,
      priority,
      summary,
      suggested_next_action: suggestedAction,
      lead_tier: tier,
      intent_signals: signals,
      budget_analysis: numericBudget > 0 ? `Estimated budget of $${numericBudget.toLocaleString()}` : 'Budget not specified',
      explanation_disclaimer: 'Estimates generated by AI based on lead input',
    });

    const latencyMs = Math.round(performance.now() - startTime);

    return {
      result,
      metadata: {
        model: 'demo-deterministic-v1',
        provider: 'mock_demo',
        prompt_tokens: 380,
        completion_tokens: 140,
        total_tokens: 520,
        latency_ms: latencyMs,
        timestamp: new Date().toISOString(),
      },
    };
  }

  async classifyText(
    input: AiTextClassificationInput,
    _options?: AiExecutionOptions
  ): Promise<{ result: AiTextClassificationResult; metadata: AiUsageMetadata }> {
    const startTime = performance.now();
    const textLower = input.text.toLowerCase();

    let matchedLabel = input.candidate_labels[0];
    let maxMatchCount = 0;

    for (const label of input.candidate_labels) {
      const words = label.toLowerCase().split(/[ _-]+/);
      let count = 0;
      for (const w of words) {
        if (w.length > 2 && textLower.includes(w)) count++;
      }
      if (count > maxMatchCount) {
        maxMatchCount = count;
        matchedLabel = label;
      }
    }

    const confidence = maxMatchCount > 0 ? 0.92 : 0.75;
    const reasoning = `Matched candidate label "${matchedLabel}" based on semantic keyword density.`;

    const result = AiTextClassificationResultSchema.parse({
      classification: matchedLabel,
      confidence,
      reasoning,
    });

    const latencyMs = Math.round(performance.now() - startTime);

    return {
      result,
      metadata: {
        model: 'demo-classifier-v1',
        provider: 'mock_demo',
        prompt_tokens: 150,
        completion_tokens: 45,
        total_tokens: 195,
        latency_ms: latencyMs,
        timestamp: new Date().toISOString(),
      },
    };
  }

  async draftEmail(
    input: AiEmailDraftInput,
    _options?: AiExecutionOptions
  ): Promise<{ result: AiEmailDraftResult; metadata: AiUsageMetadata }> {
    const startTime = performance.now();
    const sender = input.sender_name || 'The FlowPilot Team';
    const company = input.company_name || 'FlowPilot AI';

    const subject = `Re: Your Inquiry Regarding ${input.service_interest || 'Services'}`;
    const bodyText = `Hi ${input.lead_name},\n\nThank you for reaching out to ${company} regarding ${input.service_interest || 'our automation services'}.\n\nWe have reviewed your inquiry and would love to explore how we can support your goals. Based on your requirements, we recommend setting up a short 15-minute introductory call.\n\nPlease feel free to book a convenient time here: https://cal.com/flowpilot/discovery\n\nBest regards,\n${sender}`;

    const bodyHtml = `
      <div style="font-family: sans-serif; font-size: 14px; color: #333; line-height: 1.6;">
        <p>Hi ${input.lead_name},</p>
        <p>Thank you for reaching out to <strong>${company}</strong> regarding ${input.service_interest || 'our automation services'}.</p>
        <p>We have reviewed your inquiry and would love to explore how we can support your goals. Based on your requirements, we recommend setting up a short 15-minute introductory call.</p>
        <p><a href="https://cal.com/flowpilot/discovery" style="display: inline-block; padding: 10px 18px; background: #6366f1; color: #ffffff; text-decoration: none; border-radius: 6px; font-weight: bold;">Book Discovery Call</a></p>
        <p>Best regards,<br><strong>${sender}</strong></p>
      </div>
    `.trim();

    const result = AiEmailDraftResultSchema.parse({
      subject,
      body_text: bodyText,
      body_html: bodyHtml,
      call_to_action: 'Book Discovery Call',
      tone: input.tone,
      is_draft: true,
      explanation_disclaimer: 'AI-generated response draft — review before sending',
    });

    const latencyMs = Math.round(performance.now() - startTime);

    return {
      result,
      metadata: {
        model: 'demo-drafter-v1',
        provider: 'mock_demo',
        prompt_tokens: 420,
        completion_tokens: 180,
        total_tokens: 600,
        latency_ms: latencyMs,
        timestamp: new Date().toISOString(),
      },
    };
  }
}
