import type { AiProvider } from './provider';
import { wrapUntrustedInput, AI_SECURITY_SYSTEM_INSTRUCTIONS } from './provider';
import {
  AiQualificationInput,
  AiQualificationResult,
  AiQualificationResultSchema,
  AiTextClassificationInput,
  AiTextClassificationResult,
  AiTextClassificationResultSchema,
  AiEmailDraftInput,
  AiEmailDraftResult,
  AiEmailDraftResultSchema,
  AiUsageMetadata,
  AiExecutionOptions,
} from '@/types/ai';

export class OpenAiAdapter implements AiProvider {
  public readonly name = 'openai';
  private apiKey: string;
  private defaultModel: string;

  constructor(apiKey?: string, defaultModel?: string) {
    this.apiKey = apiKey || process.env.OPENAI_API_KEY || '';
    this.defaultModel = defaultModel || process.env.OPENAI_MODEL || 'gpt-4o-mini';
  }

  private async callChatCompletion(params: {
    messages: Array<{ role: 'system' | 'user' | 'assistant'; content: string }>;
    model?: string;
    temperature?: number;
    timeoutMs?: number;
    maxRetries?: number;
  }): Promise<{ content: string; usage: any; latencyMs: number }> {
    if (!this.apiKey) {
      throw new Error('OPENAI_API_KEY is not configured on the server.');
    }

    const model = params.model || this.defaultModel;
    const timeoutMs = params.timeoutMs || 20000;
    const maxRetries = params.maxRetries ?? 2;
    const temperature = params.temperature ?? 0.2;

    let attempt = 0;
    let lastError: Error | null = null;

    while (attempt <= maxRetries) {
      attempt++;
      const startTime = performance.now();
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

      try {
        const res = await fetch('https://api.openai.com/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${this.apiKey}`,
          },
          body: JSON.stringify({
            model,
            temperature,
            response_format: { type: 'json_object' },
            messages: params.messages,
          }),
          signal: controller.signal,
        });

        clearTimeout(timeoutId);
        const latencyMs = Math.round(performance.now() - startTime);

        if (!res.ok) {
          const errorBody = await res.text();
          // Retry on 429 (Rate limit) or 5xx (Server error)
          if ((res.status === 429 || res.status >= 500) && attempt <= maxRetries) {
            const backoffMs = Math.pow(2, attempt) * 500;
            await new Promise((r) => setTimeout(r, backoffMs));
            continue;
          }
          throw new Error(`OpenAI API error (${res.status}): ${errorBody}`);
        }

        const data = await res.json();
        const content = data.choices?.[0]?.message?.content || '';
        const usage = data.usage || { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 };

        return { content, usage, latencyMs };
      } catch (err: any) {
        clearTimeout(timeoutId);
        if (err.name === 'AbortError') {
          lastError = new Error(`OpenAI request timed out after ${timeoutMs}ms.`);
        } else {
          lastError = err;
        }

        if (attempt <= maxRetries) {
          const backoffMs = Math.pow(2, attempt) * 500;
          await new Promise((r) => setTimeout(r, backoffMs));
        }
      }
    }

    throw lastError || new Error('OpenAI request failed after retries.');
  }

  async qualifyLead(
    input: AiQualificationInput,
    options?: AiExecutionOptions
  ): Promise<{ result: AiQualificationResult; metadata: AiUsageMetadata }> {
    const systemPrompt = `
${AI_SECURITY_SYSTEM_INSTRUCTIONS}

You are an expert enterprise business development and lead qualification AI.
Analyze the incoming lead inquiry and evaluate commercial intent, budget fit, and conversion likelihood.

Output a valid JSON object matching the following structure:
{
  "category": "string (e.g. AI Automation, Custom Web App, Advisory)",
  "qualification_score": integer between 0 and 100,
  "priority": "low" | "medium" | "high",
  "lead_tier": "hot" | "warm" | "cold" | "unqualified",
  "summary": "1-2 sentence executive summary of the lead inquiry",
  "suggested_next_action": "concrete next sales or qualification step",
  "intent_signals": ["string", "string"],
  "budget_analysis": "short analysis of declared budget vs service scope",
  "explanation_disclaimer": "Estimates generated by AI based on lead input"
}
`.trim();

    const userPayload = `
Lead Name: ${input.lead_name || 'Not provided'}
Company: ${input.company || 'Not provided'}
Service Interest: ${input.service_interest || 'Not specified'}
Estimated Budget: ${input.estimated_budget !== undefined ? input.estimated_budget : 'Not specified'}

Raw Lead Message:
${wrapUntrustedInput(input.message, 'untrusted_lead_input')}
`.trim();

    const { content, usage, latencyMs } = await this.callChatCompletion({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPayload },
      ],
      model: options?.modelOverride,
      timeoutMs: options?.timeoutMs,
      maxRetries: options?.maxRetries,
      temperature: options?.temperature ?? 0.1,
    });

    let parsed: any;
    try {
      parsed = JSON.parse(content);
    } catch {
      throw new Error(`OpenAI returned malformed JSON: ${content.slice(0, 200)}`);
    }

    // Force default disclaimer if omitted
    if (!parsed.explanation_disclaimer) {
      parsed.explanation_disclaimer = 'Estimates generated by AI based on lead input';
    }

    const validatedResult = AiQualificationResultSchema.parse(parsed);

    return {
      result: validatedResult,
      metadata: {
        model: options?.modelOverride || this.defaultModel,
        provider: 'openai',
        prompt_tokens: usage.prompt_tokens || 0,
        completion_tokens: usage.completion_tokens || 0,
        total_tokens: usage.total_tokens || 0,
        latency_ms: latencyMs,
        timestamp: new Date().toISOString(),
      },
    };
  }

  async classifyText(
    input: AiTextClassificationInput,
    options?: AiExecutionOptions
  ): Promise<{ result: AiTextClassificationResult; metadata: AiUsageMetadata }> {
    const systemPrompt = `
${AI_SECURITY_SYSTEM_INSTRUCTIONS}

You are a precise text classification engine.
Given the candidate labels, determine the best single label classification, a confidence score between 0.0 and 1.0, and brief reasoning.

Candidate labels:
${JSON.stringify(input.candidate_labels)}

Output valid JSON:
{
  "classification": "chosen label exactly from the candidate list",
  "confidence": float between 0.0 and 1.0,
  "reasoning": "brief justification"
}
`.trim();

    const userPayload = `
Task: ${input.task_description || 'Classify text into best category'}

Text to classify:
${wrapUntrustedInput(input.text, 'untrusted_text')}
`.trim();

    const { content, usage, latencyMs } = await this.callChatCompletion({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPayload },
      ],
      model: options?.modelOverride,
      timeoutMs: options?.timeoutMs,
      maxRetries: options?.maxRetries,
    });

    let parsed: any;
    try {
      parsed = JSON.parse(content);
    } catch {
      throw new Error(`OpenAI returned malformed JSON: ${content.slice(0, 200)}`);
    }

    const validatedResult = AiTextClassificationResultSchema.parse(parsed);

    return {
      result: validatedResult,
      metadata: {
        model: options?.modelOverride || this.defaultModel,
        provider: 'openai',
        prompt_tokens: usage.prompt_tokens || 0,
        completion_tokens: usage.completion_tokens || 0,
        total_tokens: usage.total_tokens || 0,
        latency_ms: latencyMs,
        timestamp: new Date().toISOString(),
      },
    };
  }

  async draftEmail(
    input: AiEmailDraftInput,
    options?: AiExecutionOptions
  ): Promise<{ result: AiEmailDraftResult; metadata: AiUsageMetadata }> {
    const systemPrompt = `
${AI_SECURITY_SYSTEM_INSTRUCTIONS}

You are an expert sales and client communication specialist.
Draft an initial response email to a prospective lead.
The draft must be professional, compelling, and include a clear call to action.
Mark is_draft as true — drafts must remain separate from sent messages until explicitly sent.

Output valid JSON:
{
  "subject": "compelling email subject line",
  "body_text": "clean plain text formatted email body with line breaks",
  "body_html": "clean HTML formatted email body with <p>, <a>, etc.",
  "call_to_action": "the single action requested (e.g. Book 15-min Discovery Call)",
  "tone": "${input.tone}",
  "is_draft": true,
  "explanation_disclaimer": "AI-generated response draft — review before sending"
}
`.trim();

    const userPayload = `
Lead Name: ${input.lead_name}
Company: ${input.company || 'Not provided'}
Service Interest: ${input.service_interest || 'General'}
Sender: ${input.sender_name || 'Solutions Team'}
Sender Company: ${input.company_name || 'FlowPilot AI'}
Special Instructions: ${input.instructions || 'Standard introductory outreach'}

Lead Inquiry Message:
${wrapUntrustedInput(input.lead_message, 'untrusted_lead_input')}
`.trim();

    const { content, usage, latencyMs } = await this.callChatCompletion({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPayload },
      ],
      model: options?.modelOverride,
      timeoutMs: options?.timeoutMs,
      maxRetries: options?.maxRetries,
    });

    let parsed: any;
    try {
      parsed = JSON.parse(content);
    } catch {
      throw new Error(`OpenAI returned malformed JSON: ${content.slice(0, 200)}`);
    }

    parsed.is_draft = true;
    if (!parsed.explanation_disclaimer) {
      parsed.explanation_disclaimer = 'AI-generated response draft — review before sending';
    }

    const validatedResult = AiEmailDraftResultSchema.parse(parsed);

    return {
      result: validatedResult,
      metadata: {
        model: options?.modelOverride || this.defaultModel,
        provider: 'openai',
        prompt_tokens: usage.prompt_tokens || 0,
        completion_tokens: usage.completion_tokens || 0,
        total_tokens: usage.total_tokens || 0,
        latency_ms: latencyMs,
        timestamp: new Date().toISOString(),
      },
    };
  }
}
